// db/seed/xtreinos-dados.ts
// ⚠️  SÓ EDITE ESTE ARQUIVO quando tiver um novo xtreino!
// Nada de lógica aqui, só arrays com os dados brutos.

export interface XtreinoRaw {
  id: number;
  date: string;
  colocacoes: [teamName: string, q1: number, q2: number, q3: number][];
  jogadores: [teamName: string, playerName: string, q1: number, q2: number, q3: number][];
}

export const xtreinosRaw: XtreinoRaw[] = [
  // ========================================
  // XTreino 1 — 2026-04-30
  // ========================================
  {
    id: 1,
    date: "2026-04-30",
    colocacoes: [
      ["UGD Threat", 1, 1, 3],
      ["FURY", 2, 6, 6],
      ["RED", 3, 6, 6],
      ["UGD Royal", 4, 5, 6],
      ["Λつつ", 5, 2, 2],
      ["ODS", 6, 6, 6],
      ["INF", 6, 4, 6],
      ["CMF", 6, 3, 4],
      ["Eternity", 6, 6, 1],
      ["LMF", 6, 6, 5],
    ],
    jogadores: [
      ["UGD Threat", "UGD Ares", 7, 0, 0],
      ["UGD Threat", "UGD Kaze", 6, 2, 6],
      ["UGD Threat", "UGD Treon", 5, 12, 8],
      ["UGD Threat", "UGD ARISE", 6, 0, 0],
      ["UGD Threat", "UGD Neo", 0, 5, 8],
      ["UGD Threat", "Rivers AR", 0, 5, 9],
      ["FURY", "VN' FURY", 4, 0, 0],
      ["FURY", "Creedz FURY", 4, 0, 0],
      ["FURY", "perfection z", 3, 0, 0],
      ["FURY", "Diana FURY", 5, 0, 0],
      ["RED", "REÐ LANGØ", 9, 0, 0],
      ["RED", "REÐ Zadock", 2, 0, 0],
      ["RED", "REÐ M4RTINA", 8, 0, 0],
      ["RED", "REÐ APENAS", 3, 0, 0],
      ["UGD Royal", "UGD Z", 9, 0, 0],
      ["UGD Royal", "Dexz", 3, 0, 0],
      ["UGD Royal", "UGD Weenot", 8, 0, 0],
      ["UGD Royal", "OFFz", 0, 16, 0],
      ["UGD Royal", "MayaZ", 0, 8, 0],
      ["UGD Royal", "WenoTz", 0, 5, 0],
      ["UGD Light", "DEATH", 3, 3, 0],
      ["UGD Light", "UGD Psycho", 0, 0, 0],
      ["UGD Light", "I miss her", 0, 0, 0],
      ["UGD Light", "UGD Kyz", 0, 0, 0],
      ["Λつつ", "Λつつ_$CAVEIRA", 3, 0, 0],
      ["Λつつ", "Λつつ Aninha", 4, 0, 0],
      ["Λつつ", "ØNE ???", 1, 0, 0],
      ["Λつつ", "Λつつ Unknown", 1, 0, 0],
      ["Λつつ", "Striker71", 0, 2, 2],
      ["Λつつ", "『PsS-KINN-ボ", 0, 2, 1],
      ["Λつつ", "Striker81", 0, 3, 4],
      ["Λつつ", "ΛΞT Jentexz", 0, 8, 9],
      ["ODS", "[ODS].STROG", 3, 0, 0],
      ["ODS", "[ODS] vantex", 0, 0, 0],
      ["ODS", "Az Aamon", 0, 0, 0],
      ["INF", "「INF」Noxz7'", 0, 3, 0],
      ["INF", "「INF」RINNEGA", 0, 4, 0],
      ["INF", "「INF」BLAZE", 0, 2, 0],
      ["INF", "「INF」GOAT", 0, 6, 0],
      ["CMF", "CMF Lyx7", 0, 3, 8],
      ["CMF", "CMF Leo", 0, 2, 8],
      ["CMF", "CMF Stygian", 0, 3, 4],
      ["CMF", "CMF Syx", 0, 5, 8],
      ["Eternity", "Muggle 永", 0, 0, 3],
      ["Eternity", "DamønTTK 永", 0, 0, 8],
      ["Eternity", "Black 永", 0, 0, 7],
      ["Eternity", "Givas'xX 永", 0, 0, 4],
      ["LMF", "LMF_mtfacil", 0, 0, 2],
      ["LMF", "LMF_XIT", 0, 0, 2],
      ["LMF", "LMF_Boss", 0, 0, 2],
      ["LMF", "LMF_RICHIMO", 0, 0, 4],
    ],
  },
  // ========================================
  // XTreino 2 — 2026-05-07
  // ========================================
  {
    id: 2,
    date: "2026-05-07",
    colocacoes: [
      ["UGD Threat", 1, 1, 1],
      ["CMF", 2, 4, 5],
      ["INF", 3, 6, 4],
      ["LMF", 4, 2, 6],
      ["Misturado", 5, 6, 3],
      ["Eternity", 6, 3, 6],
      ["RED", 6, 5, 2],
    ],
    jogadores: [
      ["UGD Threat", "UGD Ares", 9, 16, 14],
      ["UGD Threat", "UGD Kaze", 11, 15, 8],
      ["UGD Threat", "UGD ARISE", 5, 10, 8],
      ["UGD Threat", "UGD Treon", 9, 12, 12],
      ["CMF", "CMF Stygian", 7, 2, 6],
      ["CMF", "CMF Lyx7", 12, 4, 7],
      ["CMF", "CMF Leo", 9, 6, 4],
      ["CMF", "CMF Syx", 7, 4, 6],
      ["INF", "INF Noxz7", 6, 0, 3],
      ["INF", "INF GOAT", 5, 0, 3],
      ["INF", "INF BARONI", 5, 0, 5],
      ["INF", "INF RINNEGA", 4, 0, 1],
      ["LMF", "LMF_LACERDA", 4, 0, 0],
      ["LMF", "LMF_RICHIMO", 3, 1, 0],
      ["LMF", "LMF_mtfacil", 9, 2, 0],
      ["LMF", "LMF_XIT", 4, 3, 0],
      ["LMF", "LMF_Boss", 0, 0, 0],
      ["Misturado", "REVERSE_", 0, 0, 6],
      ["Misturado", "INF RONY", 3, 0, 4],
      ["Misturado", "INF BADBOY", 2, 0, 0],
      ["Misturado", "TOP FreeKill", 0, 0, 3],
      ["Eternity", "Nofear", 0, 2, 0],
      ["Eternity", "Damøn.TTK", 0, 5, 0],
      ["Eternity", "Muggle", 0, 4, 0],
      ["Eternity", "Kennedy", 0, 6, 0],
      ["RED", "RED APENAS", 0, 5, 1],
      ["RED", "ASTRO", 0, 6, 4],
      ["RED", "REÐ snow777", 0, 2, 5],
      ["RED", "REÐ Sunraku", 0, 3, 0],
    ],
  },
  // ========================================
  // XTreino 3 — 2026-05-19
  // ========================================
  {
    id: 3,
    date: "2026-05-19",
    colocacoes: [
      ["UGD Threat", 1, 4, 1],
      ["RED", 2, 7, 4],
      ["RED Magic BR", 3, 1, 7],
      ["LMF", 4, 6, 5],
      ["KOV", 5, 5, 3],
      ["CMF", 7, 3, 2],
      ["Eternity", 6, 2, 6],
    ],
    jogadores: [
      ["UGD Threat", "UGD Treon", 11, 12, 13],
      ["UGD Threat", "UGD cool7", 8, 10, 6],
      ["UGD Threat", "UGD Kaze", 13, 1, 8],
      ["UGD Threat", "UGD ARISE", 8, 8, 4],
      ["RED", "RED snow777", 3, 0, 1],
      ["RED", "RED APENAS", 7, 0, 4],
      ["RED", "CF ALMEIDA", 0, 0, 1],
      ["RED", "LMF Boss", 5, 0, 3],
      ["RED Magic BR", "RED LANGO", 4, 7, 0],
      ["RED Magic BR", "RED KENNZY", 6, 6, 0],
      ["RED Magic BR", "MOL ADRIAN", 2, 1, 0],
      ["RED Magic BR", "LXELTINHO", 1, 5, 0],
      ["LMF", "LMF LACERDA", 2, 0, 3],
      ["LMF", "LMF CALOP12", 1, 0, 1],
      ["LMF", "LMF mtfacil", 1, 0, 5],
      ["LMF", "LMF XIT", 1, 0, 0],
      ["KOV", "KOV FushyX", 5, 2, 2],
      ["KOV", "KOV ADAN", 7, 5, 2],
      ["KOV", "TTKKAIKE", 5, 2, 0],
      ["KOV", "KOV ALONE", 0, 1, 5],
      ["CMF", "CMF Syx", 0, 7, 7],
      ["CMF", "CMF Lyx7", 0, 7, 3],
      ["CMF", "CMF MOIZO", 0, 4, 5],
      ["CMF", "CMF Stygian", 0, 3, 7],
      ["Eternity", "RED REZE", 0, 0, 0],
      ["Eternity", "Muggle", 0, 6, 0],
      ["Eternity", "Shxrk", 0, 4, 0],
    ],
  },
  // ========================================
  // XTreino 4 — 2026-05-21
  // ========================================
  {
    id: 4,
    date: "2026-05-21",
    colocacoes: [
      ["UGD Threat", 1, 3, 4],
      ["Time I", 2, 6, 3],
      ["CMF", 3, 4, 1],
      ["RED", 4, 2, 2],
      ["KOV", 5, 1, 6],
      ["Time E", 6, 5, 5],
    ],
    jogadores: [
      ["UGD Threat", "UGD Kaze", 5, 4, 6],
      ["UGD Threat", "UGD cool7", 7, 7, 6],
      ["UGD Threat", "UGD Treon", 14, 4, 3],
      ["UGD Threat", "UGD ARISE", 9, 9, 1],
      ["Time I", "hcky", 4, 0, 0],
      ["Time I", "ASTRO", 8, 0, 8],
      ["Time I", "GzmAkaza", 2, 0, 9],
      ["Time I", "AimColor", 2, 0, 0],
      ["Time I", "iDiaasz", 0, 0, 2],
      ["Time I", "Jtpe", 0, 0, 0],
      ["CMF", "CMF Leo", 8, 7, 11],
      ["CMF", "CMF Stygian", 5, 6, 5],
      ["CMF", "CMF Syx", 14, 10, 9],
      ["CMF", "CMF MOIZO", 2, 3, 7],
      ["RED", "RED APENAS", 7, 8, 7],
      ["RED", "RED- REZE", 1, 5, 0],
      ["RED", "RED-MOREIRA", 0, 2, 3],
      ["RED", "RED-Alemão", 2, 3, 2],
      ["KOV", "KOV FushyX", 1, 5, 0],
      ["KOV", "KOV ADAN", 0, 7, 0],
      ["KOV", "YoSurper", 7, 3, 0],
      ["KOV", "AET Jentexz", 1, 11, 0],
      ["Time E", "PAIN SWAN", 0, 0, 1],
      ["Time E", "Poindexter", 0, 0, 2],
      ["Time E", "ONE-Javi", 0, 0, 0],
      ["Time E", "morqesb", 0, 0, 1],
    ],
  },
  // ========================================
  // XTreino 5 — 2026-06-08
  // ========================================
  {
    id: 5,
    date: "2026-06-08",
    colocacoes: [
      ["CMF ATLANTIC", 1, 2, 1],
      ["EmE", 2, 4, 3],
      ["FURY ELITE", 3, 1, 4],
      ["UGD OLYMPIQUE", 4, 10, 12],
      ["REÐ Outlaws", 5, 9, 7],
      ["UGD Threat", 6, 11, 5],
      ["UGD LIGHT", 7, 3, 11],
      ["♱VØID×STRIKE♱", 8, 13, 6],
      ["7KW_LHETAL", 9, 7, 8],
      ["FURY ROYAL", 10, 8, 2],
      ["UGD LEGENDS", 11, 6, 9],
      ["K4F", 12, 5, 10],
      ["CMF ASSALT", 13, 12, 13],
    ],
    jogadores: [
      ["UGD OLYMPIQUE", "Weenot", 4, 4, 0],
      ["UGD OLYMPIQUE", "Duardin", 1, 0, 2],
      ["UGD OLYMPIQUE", "Striker", 3, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 4, 1, 1],
      ["UGD LEGENDS", "Santz", 3, 11, 10],
      ["UGD LEGENDS", "hell", 4, 3, 6],
      ["UGD LEGENDS", "Ohara", 2, 0, 0],
      ["UGD LEGENDS", "Rafa", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 0, 9, 4],
      ["UGD LEGENDS", "Buzeira", 1, 1, 2],
      ["UGD LIGHT", "Kyz", 5, 1, 2],
      ["UGD LIGHT", "Zann", 6, 1, 3],
      ["UGD LIGHT", "Psycho", 5, 1, 0],
      ["UGD LIGHT", "Chino", 5, 3, 5],
      ["FURY ROYAL", "VN", 9, 6, 11],
      ["FURY ROYAL", "NOKI", 4, 4, 4],
      ["FURY ROYAL", "EGOIST", 4, 6, 6],
      ["FURY ROYAL", "MARTNA", 9, 5, 2],
      ["FURY ELITE", "DIANA", 2, 1, 3],
      ["FURY ELITE", "hluydex", 2, 3, 2],
      ["FURY ELITE", "TRY", 4, 7, 4],
      ["FURY ELITE", "DEXZ", 5, 4, 3],
      ["CMF ATLANTIC", "CMF Léo", 18, 19, 17],
      ["CMF ATLANTIC", "CMF Syx", 10, 12, 23],
      ["CMF ATLANTIC", "CMF Kira", 8, 6, 11],
      ["CMF ATLANTIC", "CMF Moizo", 13, 6, 7],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 1, 0],
      ["CMF ASSALT", "CMF Max", 0, 3, 0],
      ["CMF ASSALT", "CMF Thxxxz", 3, 1, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.D_R", 0, 0, 1],
      ["♱VØID×STRIKE♱", "♱Vøid♱+gute", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.nino", 2, 0, 1],
      ["♱VØID×STRIKE♱", "™VØID°⁷⁷⁷", 1, 0, 0],
      ["REÐ Outlaws", "REÐ MoraesBC", 4, 3, 2],
      ["REÐ Outlaws", "REÐ Felpz", 4, 3, 5],
      ["REÐ Outlaws", "REÐ Skibidi", 3, 3, 0],
      ["REÐ Outlaws", "REÐ Apenas", 8, 0, 6],
      ["K4F", "k4F urso", 2, 1, 2],
      ["K4F", "K4F nine", 4, 1, 0],
      ["K4F", "K4F gui", 3, 9, 4],
      ["K4F", "Alek", 2, 0, 1],
      ["7KW_LHETAL", "(NTC)patrikm", 6, 8, 0],
      ["7KW_LHETAL", "_061_kakashi", 4, 17, 8],
      ["7KW_LHETAL", "RL.MATADOR☠️", 10, 11, 5],
      ["7KW_LHETAL", "Fefe_🎭🇧🇷", 4, 12, 7],
      ["EmE", "Yeezy", 2, 7, 4],
      ["EmE", "geldeysito", 9, 9, 17],
      ["EmE", "EME々Akaza", 4, 5, 10],
      ["EmE", "EME々Lulu", 3, 10, 8],
      ["UGD Threat", "Cool", 4, 6, 6],
      ["UGD Threat", "Treon", 6, 4, 8],
      ["UGD Threat", "Kaze", 1, 1, 4],
      ["UGD Threat", "LMF_BOSS", 2, 1, 1],
    ],
  },
  // ========================================
  // XTreino 6 — 2026-06-09
  // ========================================
  {
    id: 6,
    date: "2026-06-09",
    colocacoes: [
      ["FURY ELITE", 1, 2, 5],
      ["EmE", 2, 3, 12],
      ["CMF ATLANTIC", 3, 6, 6],
      ["UGD OLYMPIQUE", 4, 7, 4],
      ["UGD LIGHT", 5, 5, 9],
      ["♱VØID×STRIKE♱", 6, 10, 11],
      ["FURY ROYAL", 7, 1, 3],
      ["REÐ Outlaws", 8, 9, 2],
      ["K4F", 9, 8, 10],
      ["UGD Threat", 10, 4, 1],
      ["CMF ASSALT", 11, 11, 7],
      ["TROPA DO XXX", 12, 12, 8],
    ],
    jogadores: [
      ["FURY ROYAL", "VN", 3, 11, 8],
      ["FURY ROYAL", "EGOIST", 4, 20, 4],
      ["FURY ROYAL", "MARTNA", 6, 10, 12],
      ["FURY ROYAL", "OFF", 3, 10, 7],
      ["EmE", "Yeezy", 6, 4, 0],
      ["EmE", "EME々Akaza", 6, 0, 0],
      ["EmE", "MK4", 6, 8, 0],
      ["EmE", "EME々Lulu", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 5, 6, 4],
      ["UGD OLYMPIQUE", "Duardin", 5, 0, 1],
      ["UGD OLYMPIQUE", "Lorex", 4, 0, 3],
      ["UGD OLYMPIQUE", "Cants", 8, 1, 4],
      ["UGD OLYMPIQUE", "Striker", 0, 0, 0],
      ["UGD OLYMPIQUE", "Sant", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Léo", 6, 9, 4],
      ["CMF ATLANTIC", "CMF Syx", 7, 5, 8],
      ["CMF ATLANTIC", "CMF Kira", 5, 0, 0],
      ["CMF ATLANTIC", "CMF Moizo", 5, 4, 2],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 3],
      ["CMF ASSALT", "CMF Lynx7", 2, 2, 4],
      ["CMF ASSALT", "CMF Max", 3, 0, 3],
      ["CMF ASSALT", "CMF Thxxxz", 2, 2, 5],
      ["♱VØID×STRIKE♱", "♱Vøid♱.D_R", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱+gute", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.nino", 0, 0, 0],
      ["♱VØID×STRIKE♱", "™VØID°⁷⁷⁷", 0, 0, 0],
      ["♱VØID×STRIKE♱", "√Vøid√T9", 0, 0, 0],
      ["FURY ELITE", "DIANA", 4, 2, 2],
      ["FURY ELITE", "RAUAN", 11, 2, 1],
      ["FURY ELITE", "HLUYDEX", 5, 3, 1],
      ["FURY ELITE", "DEX", 5, 4, 1],
      ["FURY ELITE", "KAY", 0, 0, 0],
      ["FURY ELITE", "TRY", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 1, 1, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 2],
      ["TROPA DO XXX", "XXX 🪠🪠🪠", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 6, 2],
      ["K4F", "K4F  Éourso", 2, 0, 0],
      ["K4F", "K4F  Gui", 0, 0, 0],
      ["K4F", "K4F  Zaza", 2, 6, 0],
      ["K4F", "K4F  Nine", 0, 5, 0],
      ["K4F", "wend", 0, 0, 0],
      ["K4F", "aleke", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 4, 0, 2],
      ["UGD LIGHT", "Zann", 4, 1, 3],
      ["UGD LIGHT", "Psycho", 8, 3, 1],
      ["UGD LIGHT", "Chino", 8, 0, 3],
      ["UGD LIGHT", "Sant", 0, 0, 0],
      ["REÐ Outlaws", "REÐ  MoraesBC", 2, 0, 0],
      ["REÐ Outlaws", "REÐ  Felpz", 0, 1, 1],
      ["REÐ Outlaws", "REÐ  Skibidi", 4, 0, 3],
      ["REÐ Outlaws", "REÐ  Apenas", 2, 2, 6],
      ["UGD Threat", "Cool", 1, 10, 4],
      ["UGD Threat", "Treon", 3, 8, 5],
      ["UGD Threat", "Kaze", 1, 6, 3],
      ["UGD Threat", "Arise", 0, 0, 0],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["UGD Threat", "Santz", 2, 4, 5],
    ],
  },
  // ========================================
  // XTreino 7 — 2026-06-10
  // ========================================
  {
    id: 7,
    date: "2026-06-10",
    colocacoes: [
      ["CMF ATLANTIC", 1, 7, 3],
      ["UGD Threat + Olympique", 6, 5, 4],
      ["FURY ROYAL", 3, 3, 1],
      ["EmE", 4, 2, 10],
      ["UGD Legends", 2, 1, 6],
      ["CMF ASSALT", 7, 10, 7],
      ["FURY ELITE", 8, 4, 5],
      ["UGD LIGHT", 9, 8, 2],
      ["K4F", 10, 9, 8],
      ["♱VØID×STRIKE♱", 11, 11, 10],
    ],
    jogadores: [
      ["FURY ROYAL", "VN", 5, 11, 9],
      ["FURY ROYAL", "Egoist", 8, 5, 7],
      ["FURY ROYAL", "NG", 12, 6, 13],
      ["FURY ROYAL", "MARTNA", 11, 15, 8],
      ["FURY ROYAL", "Noki", 0, 0, 0],
      ["FURY ROYAL", "OFF", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.D_R", 1, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱+gute", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.nino", 1, 0, 0],
      ["♱VØID×STRIKE♱", "™VØID°⁷⁷⁷", 1, 0, 0],
      ["♱VØID×STRIKE♱", "√Vøid√T9", 0, 0, 0],
      ["FURY ELITE", "DIANA", 1, 1, 7],
      ["FURY ELITE", "DEX", 3, 2, 1],
      ["FURY ELITE", "SUN", 6, 9, 3],
      ["FURY ELITE", "TRY", 0, 5, 5],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["K4F", "K4F  Éourso", 1, 1, 0],
      ["K4F", "aleke", 0, 0, 0],
      ["K4F", "K4F  Zaza", 0, 1, 1],
      ["K4F", "K4F  Nine", 0, 0, 0],
      ["K4F", "wend", 2, 2, 2],
      ["UGD Threat + Olympique", "Treon", 0, 0, 0],
      ["UGD Threat + Olympique", "Kaze", 0, 0, 0],
      ["UGD Threat + Olympique", "Arise", 0, 0, 0],
      ["UGD Threat + Olympique", "LMF_BOSS", 0, 0, 0],
      ["UGD Legends", "Buzeira", 3, 2, 1],
      ["UGD Threat + Olympique", "Sant", 0, 0, 0],
      ["UGD Legends", "Hell", 3, 8, 4],
      ["UGD Legends", "Xoxoto", 14, 13, 4],
      ["UGD Threat + Olympique", "Waze", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 2, 1, 4],
      ["UGD LIGHT", "Zann", 1, 0, 0],
      ["UGD LIGHT", "Psycho", 3, 1, 1],
      ["UGD LIGHT", "Chino", 0, 0, 0],
      ["UGD LIGHT", "Sant", 0, 0, 0],
      ["UGD LIGHT", "Cool", 0, 0, 6],
      ["CMF ATLANTIC", "CMF Léo", 14, 4, 7],
      ["CMF ATLANTIC", "CMF Syx", 14, 7, 3],
      ["CMF ATLANTIC", "CMF Kira", 13, 2, 4],
      ["CMF ATLANTIC", "CMF Moizo", 9, 4, 4],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 1, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["UGD Threat + Olympique", "Weenot", 3, 9, 3],
      ["UGD Legends", "Duardin", 0, 0, 0],
      ["UGD Legends", "Lorex", 0, 0, 0],
      ["UGD Legends", "Cants", 0, 0, 0],
      ["UGD Legends", "Santz", 10, 7, 5],
      ["UGD Threat + Olympique", "Waze", 2, 7, 3],
      ["UGD Threat + Olympique", "Kaze", 5, 4, 1],
      ["UGD Threat + Olympique", "Treon", 7, 6, 11],
      ["EmE", "Nofear", 4, 6, 0],
      ["EmE", "geldeysito", 0, 0, 0],
      ["EmE", "EME々Akaza", 4, 14, 0],
      ["EmE", "MK4", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 8 — 2026-06-11
  // ========================================
  {
    id: 8,
    date: "2026-06-11",
    colocacoes: [
      ["FURY ROYAL", 1, 4, 1],
      ["UGD OLYMPIQUE / LEGENDS", 2, 2, 2],
      ["Randolinhas", 3, 1, 0],
      ["UGD LIGHT", 4, 5, 5],
      ["FURY ELITE", 5, 8, 7],
      ["TROPA DO XXX", 6, 9, 9],
      ["UGD Threat", 7, 3, 4],
      ["CMF ATLANTIC", 8, 10, 6],
      ["CMF ASSALT", 9, 7, 3],
      ["K4F", 10, 6, 8],
    ],
    jogadores: [
      ["FURY ROYAL", "MARTNA", 8, 5, 16],
      ["FURY ROYAL", "NG", 7, 6, 8],
      ["FURY ROYAL", "Egoist", 14, 9, 10],
      ["FURY ROYAL", "Noki", 7, 6, 10],
      ["FURY ROYAL", "VN", 0, 0, 0],
      ["FURY ROYAL", "OFF", 0, 0, 0],
      ["UGD OLYMPIQUE / LEGENDS", "Cants", 12, 4, 7],
      ["UGD OLYMPIQUE / LEGENDS", "Weenot", 7, 5, 9],
      ["UGD OLYMPIQUE / LEGENDS", "Xoxoto", 10, 5, 0],
      ["UGD OLYMPIQUE / LEGENDS", "Buzeira", 3, 4, 6],
      ["Randolinhas", "sinner boy", 13, 16, 0],
      ["Randolinhas", "Miag", 10, 14, 0],
      ["Randolinhas", "VAL Yzzi⁷", 18, 13, 0],
      ["Randolinhas", "7xis ╲ Tilapia", 8, 14, 0],
      ["UGD LIGHT", "Xezn⁷", 0, 0, 1],
      ["UGD LIGHT", "Psycho", 2, 3, 5],
      ["UGD LIGHT", "Chrisxz", 1, 2, 0],
      ["UGD LIGHT", "Kyz", 1, 6, 3],
      ["FURY ELITE", "TRY", 2, 3, 0],
      ["FURY ELITE", "SUN", 6, 3, 1],
      ["FURY ELITE", "DIANA", 2, 2, 1],
      ["FURY ELITE", "DEX", 1, 2, 1],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 2, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 1, 2, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 3, 3, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 4, 3, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD Threat", "Cool", 3, 6, 0],
      ["UGD Threat", "Kaze", 1, 4, 5],
      ["UGD Threat", "Treon", 4, 10, 6],
      ["UGD Threat", "Arise", 2, 1, 4],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["CMF ATLANTIC", "CMF MOZKAXR", 4, 1, 3],
      ["CMF ATLANTIC", "CMF Smoke", 2, 0, 5],
      ["CMF ATLANTIC", "CMF SANT", 2, 4, 5],
      ["CMF ATLANTIC", "CMF Moizo", 3, 2, 3],
      ["CMF ATLANTIC", "CMF Syx", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 4, 1, 7],
      ["CMF ASSALT", "Artur", 6, 0, 5],
      ["CMF ASSALT", "CMF Txxz¹", 4, 1, 5],
      ["CMF ASSALT", "CMF xeW", 0, 1, 5],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["K4F", "K4F  Éourso", 0, 1, 1],
      ["K4F", "aleke", 0, 2, 2],
      ["K4F", "wend", 2, 4, 1],
      ["K4F", "K4F  Nine", 2, 1, 4],
      ["K4F", "K4F  Zaza", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 9 — 2026-06-15
  // ========================================
  {
    id: 9,
    date: "2026-06-15",
    colocacoes: [
      ["CMF ATLANTIC", 1, 1, 3],
      ["FURY MIX (ELITE / ROYAL)", 2, 4, 5],
      ["K4F", 3, 8, 4],
      ["RED INSS", 4, 3, 1],
      ["UGD Threat", 5, 5, 2],
      ["vengeance", 6, 9, 7],
      ["CMF ASSALT", 7, 6, 9],
      ["UGD LEGENDS", 8, 2, 6],
      ["FURY CASUAL", 9, 7, 8],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD LIGHT", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["CMF ATLANTIC", "CMF Fallet", 17, 15, 14],
      ["CMF ATLANTIC", "CMF SANT", 7, 13, 4],
      ["CMF ATLANTIC", "CMF Syx⁷", 12, 14, 15],
      ["CMF ATLANTIC", "CMF M0IZO", 7, 4, 6],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["FURY MIX (ELITE / ROYAL)", "Dexz⁷ᴿʸᴸ", 5, 0, 4],
      ["FURY MIX (ELITE / ROYAL)", "B4RBOSA⁷", 10, 2, 1],
      ["FURY MIX (ELITE / ROYAL)", "NOKI FURY", 8, 4, 4],
      ["FURY MIX (ELITE / ROYAL)", "Diana FURY", 3, 3, 1],
      ["K4F", "Alek", 4, 3, 1],
      ["K4F", "K4F DUDU", 7, 1, 0],
      ["K4F", "K4F ÉoUrso", 2, 2, 1],
      ["K4F", "K4F ExuKramo", 2, 2, 1],
      ["K4F", "K4F Nine", 0, 0, 0],
      ["K4F", "Wend", 0, 0, 0],
      ["RED INSS", "RED snow777", 2, 5, 9],
      ["RED INSS", "RED APENAS", 5, 6, 4],
      ["RED INSS", "RED Thaedus⁷", 9, 5, 6],
      ["RED INSS", "RED LORD", 10, 11, 13],
      ["RED INSS", "VERON", 0, 0, 0],
      ["RED INSS", "ATREUS", 0, 0, 0],
      ["UGD Threat", "UGD cool⁷", 3, 10, 11],
      ["UGD Threat", "UGD Kaze", 1, 6, 3],
      ["UGD Threat", "UGD Treon", 12, 10, 3],
      ["UGD Threat", "UGD ARISE", 4, 6, 5],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["vengeance", "VNG NEAR★", 0, 3, 0],
      ["vengeance", "RED moraesbc", 5, 0, 0],
      ["vengeance", "Ti Pela", 1, 0, 0],
      ["vengeance", "TTKKAIKE", 3, 0, 0],
      ["vengeance", "Caveira", 0, 0, 0],
      ["vengeance", "ackerman", 0, 2, 2],
      ["vengeance", "VNG ¿¿¿", 0, 0, 2],
      ["vengeance", "VNG SCAVEIRA", 0, 1, 0],
      ["CMF ASSALT", "CMF xeW", 2, 3, 3],
      ["CMF ASSALT", "CMF Lyx7", 2, 4, 2],
      ["CMF ASSALT", "CMF Txxz¹", 1, 0, 2],
      ["CMF ASSALT", "CMF BAELTTK", 0, 3, 0],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["UGD LEGENDS", "UGD Buzeira", 0, 2, 1],
      ["UGD LEGENDS", "qgc.", 0, 2, 0],
      ["UGD LEGENDS", "CF BLAZE", 1, 3, 3],
      ["UGD LEGENDS", "UGD Santz⁷", 2, 7, 9],
      ["UGD LEGENDS", "UGD Weenot", 0, 0, 4],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 0, 0, 0],
      ["FURY CASUAL", "AM Akyra🥷", 0, 0, 0],
      ["FURY CASUAL", "FURY zLAZY⁰¹", 2, 1, 0],
      ["FURY CASUAL", "LK NPC", 0, 0, 1],
      ["FURY CASUAL", "FURY zLORHAN", 2, 2, 0],
      ["FURY CASUAL", "KILLUA", 0, 0, 0],
      ["FURY CASUAL", "VELOZZO", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 10 — 2026-06-16
  // ========================================
  {
    id: 10,
    date: "2026-06-16",
    colocacoes: [
      ["CMF ATLANTIC", 1, 4, 1],
      ["RED INSS", 2, 6, 6],
      ["FURY ROYAL / MIX (Line I)", 3, 1, 4],
      ["UGD LEGENDS", 4, 2, 3],
      ["FURY ELITE / MIX (Line H)", 5, 3, 2],
      ["UGD Threat", 6, 5, 5],
      ["CMF ASSALT", 7, 7, 7],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD LIGHT", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["CMF ATLANTIC", "CMF Teo", 9, 8, 15],
      ["CMF ATLANTIC", "CMF Syx⁷", 13, 7, 14],
      ["CMF ATLANTIC", "CMF SANT", 7, 0, 9],
      ["CMF ATLANTIC", "CMF M0IZO", 9, 8, 8],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["RED INSS", "RED APENAS", 2, 0, 2],
      ["RED INSS", "RED moraesbc", 1, 2, 1],
      ["RED INSS", "RED FELPZ", 0, 3, 0],
      ["RED INSS", "RED snow777", 0, 1, 1],
      ["FURY ROYAL / MIX (Line I)", "M4RTNA FURY", 5, 7, 8],
      ["FURY ROYAL / MIX (Line I)", "VN' FURY", 8, 7, 6],
      ["FURY ROYAL / MIX (Line I)", "Sun FURY", 5, 2, 3],
      ["FURY ROYAL / MIX (Line I)", "NOKI FURY", 7, 4, 7],
      ["UGD LEGENDS", "UGD Buzeira", 5, 1, 1],
      ["UGD LEGENDS", "qgc.", 1, 3, 3],
      ["UGD LEGENDS", "CF BLAZE", 7, 5, 5],
      ["UGD LEGENDS", "UGD XOXOTO", 6, 12, 0],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["FURY ELITE / MIX (Line H)", "Rauan FURY", 1, 2, 2],
      ["FURY ELITE / MIX (Line H)", "Dexz⁷ᴿʸᴸ", 2, 2, 1],
      ["FURY ELITE / MIX (Line H)", "B4RBOSA⁷", 6, 2, 2],
      ["FURY ELITE / MIX (Line H)", "Diana FURY", 2, 1, 1],
      ["FURY ELITE / MIX (Line H)", "TRY", 0, 0, 0],
      ["FURY ELITE / MIX (Line H)", "SLUUG", 0, 0, 0],
      ["UGD Threat", "UGD cool⁷", 4, 4, 3],
      ["UGD Threat", "UGD Treon", 7, 8, 0],
      ["UGD Threat", "UGD ARISE", 3, 3, 0],
      ["UGD Threat", "UGD Kaze", 5, 4, 4],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["CMF ASSALT", "CMF xeW", 8, 1, 1],
      ["CMF ASSALT", "CMF Lyx7", 5, 1, 1],
      ["CMF ASSALT", "CMF Txxz¹", 2, 0, 1],
      ["CMF ASSALT", "MacroSync", 0, 2, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 11 — 2026-06-17
  // ========================================
  {
    id: 11,
    date: "2026-06-17",
    colocacoes: [
      ["UGD Threat", 1, 4, 2],
      ["UGD LIGHT", 2, 9, 0],
      ["K4F", 3, 6, 8],
      ["CMF ATLANTIC", 4, 3, 4],
      ["UGD LEGENDS", 5, 8, 5],
      ["CPF VILTRUMITE", 6, 5, 6],
      ["FURY ROYAL", 7, 1, 1],
      ["CMF ASSALT", 8, 7, 3],
      ["FURY ELITE", 9, 2, 7],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["UGD Threat", "Kaze", 8, 2, 5],
      ["UGD Threat", "Arise", 11, 4, 5],
      ["UGD Threat", "Santz", 14, 3, 10],
      ["UGD Threat", "Treon", 9, 5, 9],
      ["UGD Threat", "Cool", 0, 0, 0],
      ["UGD LIGHT", "Nofear'", 2, 0, 0],
      ["UGD LIGHT", "Xezn'", 1, 0, 0],
      ["UGD LIGHT", "UGD JEM", 3, 0, 0],
      ["UGD LIGHT", "UGD Kyz`", 1, 0, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["K4F", "Alek", 2, 0, 0],
      ["K4F", "K4F NINE", 4, 0, 2],
      ["K4F", "K4F Zaza", 2, 0, 0],
      ["K4F", "Guilok07", 3, 1, 0],
      ["K4F", "NyE Wendxz", 0, 1, 0],
      ["K4F", "K4F ÉOurso", 0, 0, 0],
      ["K4F", "K4F GUI", 0, 0, 0],
      ["K4F", "K4F Aleke", 0, 0, 0],
      ["K4F", "K4F Dudu", 0, 0, 0],
      ["K4F", "wend", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Syx7", 12, 14, 10],
      ["CMF ATLANTIC", "CMF Teo", 5, 6, 0],
      ["CMF ATLANTIC", "CMF KIRA", 8, 5, 2],
      ["CMF ATLANTIC", "CMF M0IZO", 6, 3, 4],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["UGD LEGENDS", "Buzeira", 1, 0, 2],
      ["UGD LEGENDS", "Gabriel qgc", 5, 0, 1],
      ["UGD LEGENDS", "Blaze", 1, 0, 2],
      ["UGD LEGENDS", "Xoxoto", 6, 2, 4],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF gbzin", 0, 1, 0],
      ["CPF VILTRUMITE", "CPF zkrw", 0, 0, 0],
      ["CPF VILTRUMITE", "Ice", 1, 0, 0],
      ["CPF VILTRUMITE", "Biscoito", 5, 0, 0],
      ["CPF VILTRUMITE", "[CPF]xitado", 0, 1, 0],
      ["CPF VILTRUMITE", "CPF GBZIN", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF BISCOITO", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF KROM", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF ICE KILER", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF XITADO", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF LUIZ", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF PICASSO", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF SHOTTZZ", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF FLAX", 0, 0, 0],
      ["FURY ROYAL", "M4RTNA FURY", 6, 11, 12],
      ["FURY ROYAL", "NGLIFE FURY", 4, 12, 14],
      ["FURY ROYAL", "VN' FURY", 7, 5, 13],
      ["FURY ROYAL", "Egoist FURY", 5, 12, 4],
      ["CMF ASSALT", "CMF Txxz¹", 3, 0, 4],
      ["CMF ASSALT", "CMF Lyx7", 1, 0, 4],
      ["CMF ASSALT", "CMF BAELTTK", 1, 2, 3],
      ["CMF ASSALT", "CMF xeW", 1, 1, 1],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["FURY ELITE", "Diana FURY", 1, 0, 2],
      ["FURY ELITE", "Rauan FURY", 3, 2, 2],
      ["FURY ELITE", "Dexz7RYL", 0, 1, 0],
      ["FURY ELITE", "try FURY", 1, 1, 0],
      ["FURY ELITE", "DIANA", 0, 0, 0],
      ["FURY ELITE", "DEX", 0, 0, 0],
      ["FURY ELITE", "SUN", 0, 0, 0],
      ["FURY ELITE", "TRY", 0, 0, 0],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 12 — 2026-06-18
  // ========================================
  {
    id: 12,
    date: "2026-06-18",
    colocacoes: [
      ["UGD Threat", 1, 7, 1],
      ["CMF ATLANTIC", 2, 4, 3],
      ["FURY ROYAL", 3, 2, 2],
      ["FURY ELITE", 4, 1, 9],
      ["CPF VILTRUMITE", 5, 0, 6],
      ["CMF ASSALT", 6, 0, 5],
      ["UGD LEGENDS", 7, 0, 7],
      ["UGD LIGHT", 8, 5, 8],
      ["K4F", 9, 3, 4],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["UGD Threat", "Lorex", 8, 2, 12],
      ["UGD Threat", "Treon", 11, 2, 10],
      ["UGD Threat", "Kaze", 0, 1, 10],
      ["UGD Threat", "Arise", 5, 1, 4],
      ["UGD Threat", "Santz", 12, 0, 0],
      ["UGD Threat", "Cool", 0, 0, 0],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Syx", 6, 11, 7],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Leo", 5, 5, 6],
      ["CMF ATLANTIC", "CMF HISOKA", 1, 4, 3],
      ["CMF ATLANTIC", "CMF MOIZO", 3, 9, 2],
      ["FURY ROYAL", "M4RTNA FURY", 12, 8, 10],
      ["FURY ROYAL", "NGLIFE FURY", 3, 0, 0],
      ["FURY ROYAL", "VN' FURY", 6, 9, 3],
      ["FURY ROYAL", "Egoist FURY", 0, 0, 0],
      ["FURY ROYAL", "Sun FURY", 5, 5, 11],
      ["FURY ROYAL", "NOKI FURY", 10, 10, 5],
      ["FURY ELITE", "DIANA", 2, 2, 1],
      ["FURY ELITE", "DEX", 1, 0, 3],
      ["FURY ELITE", "SUN", 1, 0, 0],
      ["FURY ELITE", "TRY", 1, 0, 0],
      ["FURY ELITE", "Rauan FURY", 3, 7, 5],
      ["FURY ELITE", "Dexz7RYL", 2, 5, 0],
      ["FURY ELITE", "B4RBOSA⁷", 2, 10, 1],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["CPF VILTRUMITE", "Ice", 0, 0, 0],
      ["CPF VILTRUMITE", "Biscoito", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF gbzin", 0, 0, 0],
      ["CPF VILTRUMITE", "[CPF]xitado", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF BLAZE", 0, 0, 5],
      ["CPF VILTRUMITE", "CPF Ohara", 0, 0, 3],
      ["CPF VILTRUMITE", "qgc", 0, 0, 1],
      ["CPF VILTRUMITE", "Vw", 0, 0, 1],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Txxz¹", 9, 0, 5],
      ["CMF ASSALT", "CMF Lyx7", 3, 0, 7],
      ["CMF ASSALT", "CMF BAELTTK", 2, 0, 5],
      ["CMF ASSALT", "CMF xeW", 6, 0, 3],
      ["UGD LEGENDS", "Buzeira", 0, 0, 0],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Ohara", 6, 0, 1],
      ["UGD LEGENDS", "Xoxoto", 0, 0, 0],
      ["UGD LEGENDS", "Blaze", 1, 0, 0],
      ["UGD LEGENDS", "qgc", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 3, 0, 1],
      ["UGD LIGHT", "Psycho", 4, 1, 4],
      ["UGD LIGHT", "Zann", 1, 4, 4],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 1, 0, 0],
      ["UGD LIGHT", "Xezn⁷", 1, 0, 1],
      ["K4F", "K4F Nine", 1, 4, 1],
      ["K4F", "K4F zaza", 0, 0, 2],
      ["K4F", "K4F GUI", 0, 0, 0],
      ["K4F", "K4F Aleke", 0, 0, 0],
      ["K4F", "NyE Wendxz", 1, 8, 4],
      ["K4F", "Alek", 2, 3, 0],
      ["K4F", "K4F Éourso", 1, 0, 0],
      ["K4F", "K4F Dudu", 0, 0, 0],
      ["K4F", "wend", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
      ["UGD OLYMPIQUE", "Sant", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 13 — 2026-06-19
  // ========================================
  {
    id: 13,
    date: "2026-06-19",
    colocacoes: [
      ["CMF ATLANTIC", 1, 5, 1],
      ["FURY ELITE", 2, 2, 4],
      ["FURY ROYAL", 3, 6, 8],
      ["UGD Threat", 4, 1, 3],
      ["UGD LEGENDS", 5, 3, 6],
      ["K4F", 6, 4, 2],
      ["UGD LIGHT", 7, 7, 7],
      ["CMF ASSALT", 8, 8, 5],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
      ["CPF VILTRUMITE", 0, 0, 0],
    ],
    jogadores: [
      ["CMF ATLANTIC", "CMF Syx", 10, 14, 20],
      ["CMF ATLANTIC", "CMF KIRA", 9, 6, 12],
      ["CMF ATLANTIC", "CMF Leo", 18, 12, 8],
      ["CMF ATLANTIC", "CMF MOIZO", 4, 5, 9],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["FURY ELITE", "NOKI FURY", 11, 9, 1],
      ["FURY ELITE", "Rauan FURY", 1, 6, 4],
      ["FURY ELITE", "Dexz⁷RYL", 7, 0, 0],
      ["FURY ELITE", "DIANA FURY", 3, 2, 2],
      ["FURY ELITE", "V0XEN!", 0, 0, 1],
      ["FURY ELITE", "DEX", 0, 0, 0],
      ["FURY ELITE", "SUN", 0, 0, 0],
      ["FURY ELITE", "TRY", 0, 0, 0],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["FURY ROYAL", "M4RTNA FURY", 5, 7, 3],
      ["FURY ROYAL", "Sun FURY", 3, 2, 0],
      ["FURY ROYAL", "Asmota", 4, 2, 0],
      ["FURY ROYAL", "Egoist FURY", 3, 2, 0],
      ["UGD Threat", "Cool", 0, 0, 0],
      ["UGD Threat", "Treon", 5, 20, 12],
      ["UGD Threat", "Kaze", 3, 11, 13],
      ["UGD Threat", "Arise", 9, 4, 4],
      ["UGD Threat", "LOREX", 5, 15, 10],
      ["UGD Threat", "Santz", 0, 0, 0],
      ["UGD LEGENDS", "Buzeira", 1, 3, 3],
      ["UGD LEGENDS", "Duardin", 4, 5, 7],
      ["UGD LEGENDS", "Ohara", 3, 3, 7],
      ["UGD LEGENDS", "Hyuga⁷", 5, 4, 2],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 0, 0, 0],
      ["UGD LEGENDS", "Blaze", 0, 0, 0],
      ["UGD LEGENDS", "Gabriel qgc", 0, 0, 0],
      ["K4F", "K4F Nine", 0, 0, 2],
      ["K4F", "K4F zaza", 0, 0, 3],
      ["K4F", "Guilok07", 1, 2, 0],
      ["K4F", "K4F Éourso", 1, 1, 0],
      ["K4F", "NyE Wendxz", 0, 3, 10],
      ["K4F", "KISE", 0, 0, 3],
      ["K4F", "K4F GUI", 0, 0, 0],
      ["K4F", "K4F Aleke", 0, 0, 0],
      ["K4F", "K4F Dudu", 0, 0, 0],
      ["K4F", "wend", 0, 0, 0],
      ["UGD LIGHT", "Psycho", 2, 0, 2],
      ["UGD LIGHT", "Santz⁷", 4, 0, 0],
      ["UGD LIGHT", "V0XEN!", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Xezn⁷", 0, 0, 4],
      ["UGD LIGHT", "Dexz⁷RYL", 0, 0, 1],
      ["CMF ASSALT", "CMF Txxz¹", 3, 1, 4],
      ["CMF ASSALT", "CMF BAELTTK", 1, 2, 1],
      ["CMF ASSALT", "CMF xeW", 0, 2, 0],
      ["CMF ASSALT", "CMF Lyx7", 2, 2, 7],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
      ["UGD OLYMPIQUE", "Sant", 0, 0, 0],
      ["CPF VILTRUMITE", "Ice", 0, 0, 0],
      ["CPF VILTRUMITE", "Biscoito", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF gbzin", 0, 0, 0],
      ["CPF VILTRUMITE", "[CPF]xitado", 0, 0, 0],
    ],
  },
  // ========================================
  // XTreino 14 — 2026-06-22
  // ========================================
  {
    id: 14,
    date: "2026-06-22",
    colocacoes: [
      ["FURY ELITE", 3, 5, 1],
      ["CMF ATLANTIC", 2, 4, 2],
      ["K4F", 4, 2, 3],
      ["FURY ROYAL", 8, 1, 4],
      ["UGD Threat", 1, 3, 5],
      ["CMF ASSALT", 6, 6, 6],
      ["UGD LIGHT", 7, 7, 0],
      ["UGD LEGENDS", 5, 0, 0],
    ],
    jogadores: [
      ["FURY ELITE", "try FURY", 2, 5, 6],
      ["FURY ELITE", "Dexz⁷RYL", 1, 0, 5],
      ["FURY ELITE", "Diana FURY", 5, 0, 3],
      ["FURY ELITE", "Rauan FURY", 3, 1, 3],
      ["CMF ATLANTIC", "CMF Syx", 4, 7, 10],
      ["CMF ATLANTIC", "CMF Leo", 8, 5, 4],
      ["CMF ATLANTIC", "CMF HISOKA", 1, 4, 9],
      ["CMF ATLANTIC", "CMF MOIZO", 2, 6, 5],
      ["K4F", "Alek", 1, 0, 4],
      ["K4F", "NyE Wendxz", 0, 3, 4],
      ["K4F", "K4F NINE", 1, 0, 3],
      ["K4F", "K4F LUCAO", 2, 0, 0],
      ["K4F", "Éourso", 1, 0, 0],
      ["FURY ROYAL", "M4RTNA FURY", 13, 12, 11],
      ["FURY ROYAL", "Egoist FURY", 11, 14, 5],
      ["FURY ROYAL", "NOKI FURY", 5, 11, 8],
      ["FURY ROYAL", "VN' FURY", 8, 5, 8],
      ["UGD Threat", "Treon", 13, 7, 7],
      ["UGD Threat", "Kaze", 5, 6, 3],
      ["UGD Threat", "LOREX", 5, 6, 6],
      ["UGD Threat", "LMF_Boss", 4, 3, 3],
      ["CMF ASSALT", "CMF Txxz¹", 6, 3, 1],
      ["CMF ASSALT", "CMF xeW", 7, 1, 3],
      ["CMF ASSALT", "CMF BAELTTK", 3, 0, 3],
      ["CMF ASSALT", "CMF Lyx7", 3, 2, 0],
      ["UGD LIGHT", "UGD Psycho", 4, 0, 0],
      ["UGD LIGHT", "Dopped", 2, 1, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD LEGENDS", "ARISE", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 2, 0, 0],
      ["UGD LEGENDS", "RED MORAES", 0, 0, 0],
    ],
  },

  // ========================================
  // NOVO XTREINO? Cole um bloco novo aqui embaixo!
  // ========================================
];